resilience4j:
  circuitbreaker:
    backends:
      resilience4j-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000
        ring-buffer-size-in-half-open-state: 3
        ring-buffer-size-in-closed-state: 5
